### ISSUE TITLE
Symfony 6 (Doctrine 2.x) support?

### ISSUE THREAD

**Issue by george-viaud** [RamyHakam/multi_tenancy_bundle#20]
Looking for multi-tenancy solution for a Symfony 6 project and wanted to give this one a try as it's v5+

When trying to include I run into a dependency issue re: Doctrine ^2.0

```
Problem 1
    - Root composer.json requires hakam/multi-tenancy-bundle ^2.5 -> satisfiable by hakam/multi-tenancy-bundle[v2.5.0].
    - hakam/multi-tenancy-bundle v2.5.0 requires doctrine/annotations ^1.10 -> found doctrine/annotations[1.10.0, ..., 1.14.3] but it conflicts with your root composer.json require (^2.0).
```

**Comment by kizangadon** [comment]
@george-viaud I had the same issue, I resolved it by downgrading my doctrine/annotations to version 1.10, so in my composer.json I modified it to the following:
`"doctrine/annotations": "^1.10",`

**Comment by george-viaud** [comment]
Thank you @kizangadon  - I wonder if this project will update to support the current doctrine/annotations soon.

**Comment by Gyuroff** [comment]
Up

I will be glad if the `doctrine/annotations` is bumped to at least `^2.0`

**Comment by RamyHakam** [comment]
Thanks for rasing this issue 
I upgraded doctrine annotation within the next version
