### ISSUE TITLE
Is it possible to keep the option to select a naming strategy for the tenant databases?

### ISSUE THREAD

**Issue by HugoIrachetaZenix** [RamyHakam/multi_tenancy_bundle#23]
I was just wondering if there is an option for it or if not how difficult could it be to implement.

Thank you in advance.

**Comment by EduardKarnaukh** [comment]
Review the commit I made in the forked repository:

https://github.com/RamyHakam/multi_tenancy_bundle/commit/32c108378e39d506b1c6ac9d927025aee35b1e70

**Comment by HugoIrachetaZenix** [comment]
Yeah. With those lines we can configure it in the yaml.

Thank you.

**Comment by RamyHakam** [comment]
Thanks for your suggestion , I updated it
