### ISSUE TITLE
Deprecated the url connection parameter DBAL 3.6

### ISSUE THREAD

**Issue by emelchiordev** [RamyHakam/multi_tenancy_bundle#25]
Hi ! 

in DBAL 3.6  =>

DBAL ships with a new and configurable DSN parser that can be used to parse a database URL into connection parameters understood by DriverManager.

[Before](https://github.com/doctrine/dbal/blob/3.7.x/UPGRADE.md#before)
`$connection = DriverManager::getConnection(
    ['url' => 'mysql://my-user:t0ps3cr3t@my-host/my-database']
);`

[After](https://github.com/doctrine/dbal/blob/3.7.x/UPGRADE.md#after)
`$dsnParser  = new DsnParser(['mysql' => 'pdo_mysql']);
$connection = DriverManager::getConnection(
    $dsnParser->parse('mysql://my-user:t0ps3cr3t@my-host/my-database')
);`

I have modified the service file DbService.php in my project.

**Comment by RamyHakam** [comment]
Thanx for share this issue I will Create a PR for it
