### ISSUE TITLE
 [Question] Multi tenancy with multi database

### ISSUE THREAD

**Issue by Shotman** [RamyHakam/multi_tenancy_bundle#40]
Hello, 
Amazing bundle but I have a quick question, is it possible to have multiple tenant on multiple database severs.

Like tenant1 has it's database on 127.0.0.1 but tenant2 is on 191.168.1.56

Is it possible right now or would `src/Services/DbService.php` need to be updated to handle that ?

Thank you

**Comment by RamyHakam** [comment]
Thanks for your words,
This feature is under development right now and I pushed a new PR for this

**Comment by inventivemedia** [comment]
@RamyHakam When are you going to merge this PR in?
