### ISSUE TITLE
Getting error when running diff command on tenant

### ISSUE THREAD

**Issue by inventivemedia** [RamyHakam/multi_tenancy_bundle#45]
When running t:m:d 1 command, getting following error

"The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue."

- Default (main) entity works fine.

**Comment by panaotizz** [comment]
Try adding the server version on the DATABASE_URL value in your .env file 
for example: DATABASE_URL="mysql://root@localhost:3306/dbname?serverVersion=mariadb-10.4.28"

If that does not work, try deleting all migration files from project and DB and run the diff command to generate it again (do this if you don't care about losing your migration files)
